server:
  port : 8081
spring:
# Database
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices
    username: zola
    password:
# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect