server:
  port : 8080
spring:
# Database
  datasource:
    url: "jdbc:postgresql://localhost:5432/invoices"
    username: "zola"
    password:
# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR